### ISSUE TITLE
Security Requirements

### ISSUE THREAD

**Issue by Brendon127** [5-guys-1-branch/capstone-documentation#11]
Specify any requirements regarding security or privacy issues surrounding use
of the product or protection of the data used or created by the product. Define
any user identity authentication requirements. Refer to any external policies or
regulations containing security issues that affect the product. Define any
security or privacy certifications that must be satisfied.

**Comment by Brendon127** [comment]
There is a rogue bullet under Usability

**Comment by LenBekker** [comment]
> There is a rogue bullet under Usability

Fixed.

**Comment by u14177553** [comment]
Looks Good
